### ISSUE TITLE
error: git-vain died of signal 6

### ISSUE THREAD

**Issue by T-Pham** [will/git-vain#1]
Hey, thanks for making this tool.
I'm trying the tool but constantly get this error "error: git-vain died of signal 6". Is there any way you would suggest to avoid the error?

**Comment by richardnias** [comment]
I didn't get this error when I built a week ago, but I do get it today. any chance some dependency has updated and caused issues?

the machine having issues is a early 2015 macbook pro, running macos 10.13.5 Beta. not sure right now about the machine that works but can check tomorrow.

**Comment by will** [comment]
Sorry I have no idea how to help

**Comment by richardnias** [comment]
update... it works on my mid 2015 macbook pro running version 10.13.4... guessing it's something to do with the macos version...

will, i hope you understand that this is a Very Important part of my workflow and it is _essential_ we get this fixed immediately.

jk you're ok i'm not sure why i care

**Comment by T-Pham** [comment]
I tried on my mid-2014 macbook maybe it doesn't work there. Anyway, this is not something important as we all just want to try it for fun I think. I will close the issue.

**Comment by thommahoney** [comment]
I ran into this problem and opened a PR that seems to fix it. https://github.com/will/git-vain/pull/2
